import re
from fastapi import APIRouter, HTTPException, Path
from fastapi.responses import FileResponse
from typing import List, Dict, Any
from backend.services.project_service import project_service

router = APIRouter()

@router.get("/overview")
def get_overview():
    """
    Returns concise metadata overview of the EcoTwin platform.
    """
    try:
        return project_service.get_project_overview()
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/workflow")
def get_workflow():
    """
    Returns visual operations pipeline mapping.
    """
    try:
        return project_service.get_workflow_map()
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/notebooks")
def get_notebooks():
    """
    Returns list of discovered Jupyter notebooks.
    """
    try:
        return project_service.list_notebooks()
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/notebooks/{id}")
def get_notebook(id: str = Path(..., description="Target notebook filename e.g. '01_dataset_audit.ipynb'")):
    """
    Returns full details, cell blocks, and AST function listings for a notebook.
    """
    if not re.match(r"^[0-9a-zA-Z_\-\.]+\.ipynb$", id):
        raise HTTPException(status_code=400, detail="Invalid notebook filename format.")
        
    try:
        return project_service.get_notebook_details(id)
    except FileNotFoundError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/outputs")
def get_outputs():
    """
    Returns mapped images generated by notebooks.
    """
    try:
        return project_service.get_output_gallery()
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/models")
def get_models():
    """
    Returns active models registry metadata.
    """
    try:
        return project_service.get_models_overview()
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/raw-figure/{filename}")
def get_raw_figure(filename: str = Path(..., description="Image filename to fetch safely")):
    """
    Safe proxy route to serve figure images. Prevents path traversal and exposes correct media mime types.
    """
    if not re.match(r"^[0-9a-zA-Z_\-\.]+\.(png|jpg|jpeg|svg|webp)$", filename):
        raise HTTPException(status_code=400, detail="Invalid image filename format.")
        
    # Check main figures folder and spatial subfolder
    root_fig_path = project_service.figures_dir / filename
    spatial_fig_path = project_service.figures_dir / "spatial" / filename
    
    target_path = None
    if root_fig_path.exists():
        target_path = root_fig_path
    elif spatial_fig_path.exists():
        target_path = spatial_fig_path
        
    if not target_path:
        raise HTTPException(status_code=404, detail=f"Figure '{filename}' not found.")
        
    # Expose FileResponse safely
    return FileResponse(str(target_path))
